# Generated by Django 5.2.7 on 2025-10-30 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0002_initial'),
        ('finance', '0001_initial'),
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='procurement',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurements', to='finance.budget'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procurement',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procurement',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurements', to='hr.department'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_requests', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procurementline',
            name='asset_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_lines', to='asset.assetcategory'),
        ),
        migrations.AddField(
            model_name='procurementline',
            name='procurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='asset.procurement'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendor',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendor',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procurement',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurements', to='asset.vendor'),
        ),
        migrations.AddField(
            model_name='license',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licenses', to='asset.vendor'),
        ),
        migrations.AddField(
            model_name='assetmaintenance',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances', to='asset.vendor'),
        ),
        migrations.AddField(
            model_name='asset',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='asset.vendor'),
        ),
        migrations.AddIndex(
            model_name='assetassignment',
            index=models.Index(fields=['asset', 'is_active'], name='asset_assig_asset_i_229f1d_idx'),
        ),
        migrations.AddIndex(
            model_name='assetassignment',
            index=models.Index(fields=['employee', 'is_active'], name='asset_assig_employe_08e084_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['code'], name='vendors_code_42adf1_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['status'], name='vendors_status_079e23_idx'),
        ),
        migrations.AddIndex(
            model_name='procurement',
            index=models.Index(fields=['procurement_number'], name='procurement_procure_776e47_idx'),
        ),
        migrations.AddIndex(
            model_name='procurement',
            index=models.Index(fields=['status'], name='procurement_status_f070de_idx'),
        ),
        migrations.AddIndex(
            model_name='procurement',
            index=models.Index(fields=['requested_by'], name='procurement_request_f54763_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['license_number'], name='licenses_license_09b588_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['status'], name='licenses_status_c60f55_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['end_date'], name='licenses_end_dat_122f76_idx'),
        ),
        migrations.AddIndex(
            model_name='assetmaintenance',
            index=models.Index(fields=['maintenance_number'], name='asset_maint_mainten_110377_idx'),
        ),
        migrations.AddIndex(
            model_name='assetmaintenance',
            index=models.Index(fields=['asset'], name='asset_maint_asset_i_7f7bfe_idx'),
        ),
        migrations.AddIndex(
            model_name='assetmaintenance',
            index=models.Index(fields=['status'], name='asset_maint_status_7ab773_idx'),
        ),
        migrations.AddIndex(
            model_name='assetmaintenance',
            index=models.Index(fields=['scheduled_date'], name='asset_maint_schedul_1fba25_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_number'], name='assets_asset_n_43d081_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status'], name='assets_status_326766_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['assigned_to'], name='assets_assigne_36a4dc_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['serial_number'], name='assets_serial__240171_idx'),
        ),
    ]
